applications/persona/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"  # Nombre de url's

urlpatterns = [
    path("", views.InicioView.as_view(), name="inicio"),
    path("create_empleado/", views.EmpleadoCreateView.as_view(), name="crear_empleado"),
    path("lista_empleados/", views.ListEmpleados.as_view(), name="lista_empleados"),
    path("detalle_empleado/<pk>/", views.EmpleadoDetailView.as_view(), name="empleado"),
    path("lista_area/<name>/", views.ListEmpleadosArea.as_view(), name="empleado_area"),
    path("lista_area_admin/", views.ListEmpleadosAdmin.as_view(), name="empleado_admin"),
    path("update_view/<pk>/", views.EmpleadoUpdateView.as_view(), name="empleado_update"),
    path("delete_view/<pk>/", views.EmpleadoDeleteView.as_view(), name="empleado_delete"),
    # # path('lista_job/<job>/', views.ListEmpleadosJob.as_view()),
    # path("buscar_empleados/", views.ListBuscarEmpleados.as_view()),
    # path("lista_skills/", views.ListaHabilidades.as_view(), name="habilidades"),
    # path("success_view/", views.SuccessView.as_view(), name="success"),
]

project01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    # URL de app creadas
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),

] 
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from django.forms import CharField
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.


class Habilidades(models.Model):
    habilidad = models.CharField("Habilidad", max_length=50)

    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural = "Habilidades Empleados"

    def __str__(self):
        return self.habilidad


class Empleado(models.Model):
    JOB_CHOISES = (
        ("0", "Contador"),
        ("1", "Administrador"),
        ("2", "Economista"),
        ("3", "Otro"),
    )
    first_name = models.CharField("Nombres", max_length=60)
    last_name = models.CharField("Apellidos", max_length=60)
    full_name = models.CharField("Nombres completos", max_length=120, blank=True)
    job = models.CharField("Trabajo", max_length=1, choices=JOB_CHOISES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="empleado/%Y-%m-%d", blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    resume = RichTextField()

    class Meta:
        verbose_name = "Mi empleado"
        verbose_name_plural = "Empleados de la empresa"
        ordering = ["-first_name", "last_name"]
        unique_together = ("first_name", "departamento")

    def __str__(self):
        return self.first_name

applications/persona/forms.py
from django import forms

from .models import Empleado


class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (
            "first_name",
            "last_name",
            "job",
            "departamento",
            "avatar",
            "habilidades",
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from multiprocessing import context
from pyexpat import model
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)

# models
from applications.departamento.models import Departamento
from .models import Empleado
# forms
from .forms import EmpleadoForm


# Create your views here.

class InicioView(TemplateView):
    template_name = 'inicio.html'


class EmpleadoCreateView(CreateView):
    template_name = "persona/create_empleado.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy("persona_app:empleado_admin")  # Se redirecciona a la url con nombre 'success'

    def form_valid(self, form):  # Metodo que valida el post para guardarlo en la bd
        # logica del proceso
        empleado = form.save()
        empleado.full_name = empleado.first_name + " " + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class ListEmpleados(ListView):
    template_name = "persona/lista_empleados.html"
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(full_name__icontains=palabra_clave)
        return lista    
        

class ListEmpleadosArea(ListView):
    template_name = "persona/lista_area.html"
    context_object_name = 'empleados'


    def get_queryset(self):
        area = self.kwargs["name"]
        lista = Empleado.objects.filter(departamento__name=area)
        return lista


class ListEmpleadosAdmin(ListView):
    template_name = "persona/lista_area_admin.html"
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/empleado_update.html"
    model = Empleado
    fields = ["first_name", "last_name", "job", "departamento", "habilidades"]
    success_url = reverse_lazy("persona_app:empleado_admin")

    def post(self, request, *args, **kwargs):  # Metodo que intercepta el post desde el html antes de validarlo
        self.object = self.get_object()
        print("======METODO post======")  # identificar el orden en que se ejecutan y validan metodos
        print("=====PARAMETRO request=======")
        print(request.POST)  # muestra un diccionario con los datos del post
        print(request.POST["last_name"])  # recupera el valor de 'last_name'
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        print("======METODO form_valid======")  # identificar el orden en que se ejecutan y  validan metodos
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    template_name = "persona/empleado_delete.html"
    model = Empleado
    success_url = reverse_lazy("persona_app:empleado_admin")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detalle_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del Mes'
        return context

        
# """class ListEmpleadosJob(ListView):
#     template_name = 'persona/lista_job.html'
   

#     def get_queryset(self):
#         area = self.kwargs['job']
#         lista = Empleado.objects.filter(
#         job = area 
#     )
#         return lista"""


# class ListBuscarEmpleados(ListView):
#     template_name = "persona/buscar_empleados.html"
#     context_object_name = "empleados"

#     def get_queryset(self):
#         palabra_clave = self.request.GET.get("kword", '')
#         lista = Empleado.objects.filter(
#             first_name=palabra_clave
#         )
#         return lista


# class ListaHabilidades(ListView):
#     template_name = "persona/lista_skills.html"
#     paginate_by = 4
#     ordering = "habilidades"
#     context_object_name = "habilidad"

#     def get_queryset(self):
#         empleado = Empleado.objects.get(id=2)
#         return empleado.habilidades.all()

    
# class SuccessView(TemplateView):
#     template_name = "persona/success_view.html"

templates/persona/create_empleado.html
{% extends 'base.html' %}


{% block title %}
Crear Empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %} <!-- Sirve para servir archivos media: enctype="multipart/form-data"-->
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajos:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamentos:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>habilidades:
                        {{ form.habilidades }}
                    </label>
                </div> <div class="cell large-6">
                    <label>Avatar:
                        {{ form.avatar }}
                    </label>
                </div>
                <div class="cell ">
                    <button  type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/persona/detalle_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ object.first_name }}
{% endblock title %}


{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
                {{ object.get_job_display }}
            </div>
            {% if object.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}
                <img src="{% static 'img/20.jpg' %}">
            {% endif %}  
            <div class="card-section">
                <h4>{{ object.full_name}}</h4>
                <p>{{  object.last_name }}</p>
                <p>{{  object.departamento.name }}</p>
                <p><span class="label">habilidades:</span></p>
                <ul class="vertical-menu">
                    
                    {% for h in object.habilidades.all  %}
                        <li>
                           <p>{{ h.habilidad }}</p>
                        </li>
                    {% endfor %}
                        
                </ul>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

<body>

    <h1> Hello, This is from detalle_empleado.html</h1>
    <p>{{ empleado.first_name }}</p>
    <p>{{ empleado.last_name }}</p>
    <p>{{ empleado.departamento }}</p>
    <p>{{ empleado.habilidades }}</p>

</body>

</html>

templates/persona/empleado_delete.html
{% extends 'base.html' %}


{% block title %}

{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{ object.full_name }}</h1>
        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Borrar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/persona/empleado_update.html
{% extends 'base.html' %}


{% block title %}
Editar Empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajos:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamentos:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>habilidades:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell ">
                    <button  type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/persona/lista_area.html
{% extends 'base.html' %}

{% block title %}
Lista Empleados por departamento
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Empleados por area:</div>
        <div class="cell">
            <table class="">
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombre</th>
                        <th width="150">Apelidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button primary" href="{% url 'persona_app:empleado' e.id %}">Ver</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/lista_area_admin.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
    </div>
    <div class="cell">
        <table class="">
            <thead>
                <tr>
                    <th width="200">ID</th>
                    <th>Nombre</th>
                    <th width="150">Apelidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Detalle</th>
                </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td>
                        <a class="button success" href="{% url 'persona_app:empleado_update' e.id %}">Editar</a>
                    </td>
                    <td>
                        <a class="button alert" href="{% url 'persona_app:empleado_delete' e.id %}">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="cell">
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
                </li>
                {% endif %}

                {% for pagina in paginator.page_range %}

                {% if pagina == page_obj.number %}
                <li class="current"><span class="show-for-sr"></span>{{ pagina }}</li>
                {% else %}
                <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{ page_obj.next_page_number }}">siguiente</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
    </div>
    <div class="cell">
        <table class="">
            <thead>
                <tr>
                    <th width="200">ID</th>
                    <th>Nombre</th>
                    <th width="150">Apelidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Detalle</th>
                </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td><a class="button primary" href="{% url 'persona_app:empleado' e.id %}">Ver</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="cell">
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
                </li>
                {% endif %}

                {% for pagina in paginator.page_range %}

                {% if pagina == page_obj.number %}
                <li class="current"><span class="show-for-sr"></span>{{ pagina }}</li>
                {% else %}
                <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{ page_obj.next_page_number }}">siguiente</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock content %}