applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path("lista_departamento/", views.DepartamentoListView.as_view(), name="lista_departamento"),
    path("nuevo_departamento/", views.NewDepartmentoView.as_view(), name="nuevo_departamento"),
]

applications/persona/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"  # Nombre de url's

urlpatterns = [
    path("", views.InicioView.as_view(), name="inicio"),
    path("create_empleado/", views.EmpleadoCreateView.as_view(), name="crear_empleado"),
    path("lista_empleados/", views.ListEmpleados.as_view(), name="lista_empleados"),
    path("detalle_empleado/<pk>/", views.EmpleadoDetailView.as_view(), name="empleado"),
    path("lista_area/<name>/", views.ListEmpleadosArea.as_view(), name="empleado_area"),
    path("lista_area_admin/", views.ListEmpleadosAdmin.as_view(), name="empleado_admin"),
    path("update_view/<pk>/", views.EmpleadoUpdateView.as_view(), name="empleado_update"),
    path("delete_view/<pk>/", views.EmpleadoDeleteView.as_view(), name="empleado_delete"),
    # # path('lista_job/<job>/', views.ListEmpleadosJob.as_view()),
    # path("buscar_empleados/", views.ListBuscarEmpleados.as_view()),
    # path("lista_skills/", views.ListaHabilidades.as_view(), name="habilidades"),
    # path("success_view/", views.SuccessView.as_view(), name="success"),
]

project01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    # URL de app creadas
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),

] 
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<!--Header-->
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'persona_app:lista_empleados' %}">Listar</a>
          </li>
        <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleado_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleados"></li>
        <li><a href="{% url 'persona_app:crear_empleado' %}" class="button">Registrar</a></li>
      </ul>
    </div>
</div>