applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path("lista_departamento/", views.DepartamentoListView.as_view(), name="lista_departamento"),
    path("nuevo_departamento/", views.NewDepartmentoView.as_view(), name="nuevo_departamento"),
]

applications/persona/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"  # Nombre de url's

urlpatterns = [
    path("", views.InicioView.as_view(), name="inicio"),
    path("create_empleado/", views.EmpleadoCreateView.as_view(), name="crear_empleado"),
    path("lista_empleados/", views.ListEmpleados.as_view(), name="lista_empleados"),
    path("detalle_empleado/<pk>/", views.EmpleadoDetailView.as_view(), name="empleado"),
    path("lista_area/<name>/", views.ListEmpleadosArea.as_view(), name="empleado_area"),
    path("lista_area_admin/", views.ListEmpleadosAdmin.as_view(), name="empleado_admin"),
    path("update_view/<pk>/", views.EmpleadoUpdateView.as_view(), name="empleado_update"),
    path("delete_view/<pk>/", views.EmpleadoDeleteView.as_view(), name="empleado_delete"),
    # # path('lista_job/<job>/', views.ListEmpleadosJob.as_view()),
    # path("buscar_empleados/", views.ListBuscarEmpleados.as_view()),
    # path("lista_skills/", views.ListaHabilidades.as_view(), name="habilidades"),
    # path("success_view/", views.SuccessView.as_view(), name="success"),
]

project01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    # URL de app creadas
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),

] 
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Alias', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    def __str__(self):
        return self.name

applications/departamento/forms.py
import imp
from django import forms

class NewDepartmentForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import FormView

from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartmentForm

# Create your views here.


class DepartamentoListView(ListView):
    template_name = "departamento/lista_departamento.html"
    model = Departamento
    context_object_name = 'departamentos'

    
class NewDepartmentoView(FormView):
    template_name = 'departamento/nuevo_departamento.html'
    form_class = NewDepartmentForm
    success_url = reverse_lazy("departamento_app:lista_departamento")

    def form_valid(self, form):
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['shortname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']    #recuperando los datos desde el form
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellidos,
            job='1',
            departamento=depa,
        )
        return super(NewDepartmentoView, self).form_valid(form)

templates/departamento/lista_departamento.html
{% extends 'base.html' %}


{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x" >
            <h1 class="cell">Lista Departamento</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos  %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.short_name }}</td>
                            <td><a class="button primary" href="{% url 'persona_app:empleado_area'  departamento.name %}">Ver empleados</a></td>
                        </tr>
                        {% endfor %}  
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/departamento/nuevo_departamento.html
{% extends 'base.html' %}


{% block title %}
Registrar departamentos
{% endblock title %}


{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombre:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido:
                    {{ form.apellidos }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{ form.departamento }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Alias:
                    {{ form.shortname }}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}